spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml








